import type { ModelRouteInput } from "@/domain";

/**
 * Curated EU LLM route dataset — captured June 2026.
 *
 * Prices are $/1M tokens as published by vendors (mixed USD/EUR). TTFT and
 * throughput are median benchmarks (Artificial Analysis / vendor) and vary with
 * region, load and prompt length. Reliability fields:
 *   - slaPct          vendor-published monthly uptime SLA (null = none public)
 *   - observedUptime  third-party 90-day observed uptime (null = unmeasured)
 *   - availabilityRisk operational "will it be there at deploy time" risk
 *
 * Sources are listed in README.md. Verify pricing on the official page before
 * committing to production.
 */
export const CATALOG: ReadonlyArray<ModelRouteInput> = [
  // ── Tier A · EU-sovereign (no CLOUD Act reach) ──────────────────────────────
  {
    id: "mistral-small-4",
    name: "Mistral Small 4",
    maker: "Mistral",
    route: "Mistral La Plateforme (FR)",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.1,
    outputPrice: 0.3,
    throughput: 172,
    ttft: 0.66,
    latest: true,
    note: "Apache 2.0. Best sovereign workhorse for classify/extract/draft.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "medium",
    reliabilityNote:
      "Single sovereign vendor; ~79% third-party 90-day uptime + latency spikes observed. Custom SLA only on Enterprise. Pair with Scaleway/OVH failover.",
  },
  {
    id: "mistral-small-3-2",
    name: "Mistral Small 3.2",
    maker: "Mistral",
    route: "OVHcloud / Scaleway (FR)",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.09,
    outputPrice: 0.28,
    throughput: 165,
    ttft: 0.65,
    note: "Cheapest capable Mistral; hosted on sovereign infra with real SLAs.",
    slaPct: 99.5,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "OVHcloud AI Endpoints 99.5% SLA / Scaleway 99.9% serverless SLA. Two sovereign hosts for the same weights.",
  },
  {
    id: "ministral-3-8b",
    name: "Ministral 3 8B",
    maker: "Mistral",
    route: "Mistral La Plateforme (FR)",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.15,
    outputPrice: 0.15,
    throughput: 170,
    ttft: 0.55,
    note: "Classification / extraction / intent.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "medium",
    reliabilityNote: "Mistral-hosted; same single-vendor caveat as Small 4. Mirror on OVH for failover.",
  },
  {
    id: "ministral-3-3b",
    name: "Ministral 3 3B",
    maker: "Mistral",
    route: "Mistral / OVHcloud (FR)",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.1,
    outputPrice: 0.1,
    throughput: 187,
    ttft: 0.5,
    note: "Fastest + cheapest Mistral. Routing / triage tier.",
    slaPct: 99.5,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Available on OVHcloud (99.5% SLA) as well as Mistral — host on OVH to get the SLA.",
  },
  {
    id: "mistral-medium-3-5",
    name: "Mistral Medium 3.5",
    maker: "Mistral",
    route: "Mistral / Scaleway (FR)",
    tier: "A",
    mode: "configurable",
    openness: "open-weight",
    inputPrice: 1.5,
    outputPrice: 7.5,
    throughput: 158,
    ttft: 1.78,
    latest: true,
    note: "Highest Mistral quality. Toggle reasoning_effort — one model, two speeds.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Run on Scaleway (99.9%) for the SLA; Mistral-native as secondary.",
  },
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    maker: "Mistral",
    route: "Mistral / Scaleway / Bedrock EU",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.5,
    outputPrice: 1.5,
    throughput: 206,
    ttft: 1.1,
    latest: true,
    note: "Frontier-class, 262K context. Cheapest in its tier.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Scaleway sovereign (99.9%); also on Bedrock EU as a residency fallback.",
  },
  {
    id: "magistral-medium-1-2",
    name: "Magistral Medium 1.2",
    maker: "Mistral",
    route: "Mistral La Plateforme (FR)",
    tier: "A",
    mode: "reasoning",
    openness: "proprietary",
    inputPrice: 2.0,
    outputPrice: 5.0,
    throughput: 120,
    ttft: 1.5,
    latest: true,
    note: "Dedicated sovereign reasoning. Rivals o3-class.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "medium",
    reliabilityNote: "Premier model, Mistral-only. No open-weight mirror — escalation path, not a default.",
  },
  {
    id: "magistral-small-1-2",
    name: "Magistral Small 1.2",
    maker: "Mistral",
    route: "Mistral / Scaleway (FR)",
    tier: "A",
    mode: "reasoning",
    openness: "open-weight",
    inputPrice: 0.5,
    outputPrice: 1.5,
    throughput: 130,
    ttft: 1.2,
    note: "Open-weight reasoning; price = Large 3. Hostable on Scaleway.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Open weights → host on Scaleway (99.9%) to escape single-vendor risk.",
  },
  {
    id: "gpt-oss-20b-ovh",
    name: "gpt-oss-20b",
    maker: "OpenAI OSS",
    route: "OVHcloud (FR)",
    tier: "A",
    mode: "configurable",
    openness: "open-source",
    inputPrice: 0.04,
    outputPrice: 0.15,
    throughput: 307,
    ttft: 0.45,
    note: "Apache 2.0. Lowest EUR price. Reasoning toggle.",
    slaPct: 99.5,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "OVHcloud AI Endpoints 99.5% SLA per individual model endpoint, 400 RPM rate limit, Gravelines DC, zero data retention.",
  },
  {
    id: "gpt-oss-20b-stackit",
    name: "gpt-oss-20b",
    maker: "OpenAI OSS",
    route: "STACKIT AI Model Serving (DE/AT)",
    tier: "A",
    mode: "configurable",
    openness: "open-source",
    inputPrice: 0.15,
    outputPrice: 0.25,
    throughput: 250,
    ttft: 0.7,
    note: "STACKIT Standard tier. German sovereign OpenAI-compatible route.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote:
      "Official STACKIT May 2026 pricing: Standard LLM tier €0.15/€0.25 per 1M tokens; one OpenAI-compatible base URL, GDPR+C5+ISO27001 posture.",
  },
  {
    id: "gpt-oss-120b",
    name: "gpt-oss-120b",
    maker: "OpenAI OSS",
    route: "Scaleway / OVH / STACKIT",
    tier: "A",
    mode: "configurable",
    openness: "open-source",
    inputPrice: 0.15,
    outputPrice: 0.6,
    throughput: 300,
    ttft: 0.4,
    latest: true,
    note: "Cheapest capable sovereign reasoner. Same weights on 3 sovereign hosts.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Multi-host (Scaleway 99.9% / OVH 99.5% / STACKIT) — strongest sovereign availability of any single model.",
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    maker: "Meta",
    route: "STACKIT / OVH / IONOS",
    tier: "A",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.45,
    outputPrice: 0.65,
    throughput: 120,
    ttft: 0.9,
    note: "Llama Community licence. Broadly hosted across DE+FR sovereign clouds.",
    slaPct: 99.5,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Hosted on STACKIT (DE, C5+ISO27001), OVH (99.5%) and IONOS (DE) — triple sovereign redundancy.",
  },
  {
    id: "qwen3-5-397b",
    name: "Qwen3.5-397B-A17B",
    maker: "Alibaba",
    route: "OVHcloud / Scaleway (FR)",
    tier: "A",
    mode: "reasoning",
    openness: "open-source",
    inputPrice: 0.6,
    outputPrice: 3.6,
    throughput: 90,
    ttft: 1.4,
    latest: true,
    note: "Frontier open-weight reasoning (Apache 2.0).",
    slaPct: 99.5,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "OVHcloud / Scaleway sovereign hosting.",
  },
  {
    id: "deepseek-v3-2",
    name: "DeepSeek V3.2",
    maker: "DeepSeek",
    route: "Nebius / Scaleway (EU)",
    tier: "A",
    mode: "configurable",
    openness: "open-weight",
    inputPrice: 0.28,
    outputPrice: 0.42,
    throughput: 220,
    ttft: 0.9,
    latest: true,
    note: "Via Nebius (NL/EU) or Scaleway, zero-retention.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Nebius Token Factory 99.9% SLA (100M tok/min autoscale); Scaleway as second sovereign host.",
  },

  // ── Tier B · EU-residency under a US vendor (CLOUD Act exposure) ─────────────
  {
    id: "azure-gpt-5-nano",
    name: "gpt-5-nano",
    maker: "OpenAI",
    route: "Azure EU Data Zone (SE)",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 0.05,
    outputPrice: 0.4,
    throughput: 150,
    ttft: 0.85,
    note: "Residency via Sweden Central. CLOUD Act exposure remains.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "high",
    reliabilityNote:
      "Azure SLA is 99.9% but quota ≠ guaranteed capacity: deployments can fail, Data Zone Standard shares one EU quota pool (429 contention under burst), and newest models lag EU rollout. This is the instability you hit.",
  },
  {
    id: "azure-gpt-5-mini",
    name: "gpt-5-mini (reference)",
    maker: "OpenAI",
    route: "Azure EU Data Zone (SE)",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 0.25,
    outputPrice: 2.0,
    throughput: 101,
    ttft: 1.0,
    note: "Baseline reference. Minimal reasoning ~101 t/s.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "high",
    reliabilityNote: "Same Azure EU Data Zone capacity/quota constraints as gpt-5-nano.",
  },
  {
    id: "azure-gpt-5-4-nano",
    name: "gpt-5.4-nano",
    maker: "OpenAI",
    route: "Azure EU Data Zone (pending)",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 0.2,
    outputPrice: 1.25,
    throughput: 230,
    ttft: 0.7,
    latest: true,
    note: "Mar 2026 model — NOT in EU Data Zone Standard as of Jun 2026.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "high",
    reliabilityNote:
      "Only Global Standard (worldwide routing, not EU-safe) in EU regions. MS won't confirm EU Data Zone before gpt-4.1-mini retires Oct 2026. Effectively undeployable EU-compliant today.",
  },
  {
    id: "vertex-gemini-2-5-flash-lite",
    name: "Gemini 2.5 Flash-Lite",
    maker: "Google",
    route: "Vertex europe-west4 (NL)",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 0.1,
    outputPrice: 0.4,
    throughput: 214,
    ttft: 0.29,
    note: "Best price/speed in tier B. Disable thinking for fast path.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Vertex AI ~99.9% SLO, single-region europe-west4 endpoint is mature and stable.",
  },
  {
    id: "vertex-gemini-3-1-flash-lite",
    name: "Gemini 3.1 Flash-Lite",
    maker: "Google",
    route: "Vertex europe-west4 (NL)",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 0.25,
    outputPrice: 1.5,
    throughput: 230,
    ttft: 0.4,
    latest: true,
    note: "Feb 2026. Smarter than 2.5, slightly pricier.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "medium",
    reliabilityNote: "Newest Gemini single-region EU endpoints can lag the global launch — verify europe-west4 availability.",
  },
  {
    id: "bedrock-claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    maker: "Anthropic",
    route: "AWS Bedrock EU (Frankfurt)",
    tier: "B",
    mode: "non-reasoning",
    openness: "proprietary",
    inputPrice: 1.0,
    outputPrice: 5.0,
    throughput: 100,
    ttft: 0.7,
    note: "Bedrock EU has residency; Azure Foundry has NO Claude EU residency.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Bedrock 99.9% regional SLA + EU-geo inference profile. The compliant way to reach Claude in the EU.",
  },
  {
    id: "bedrock-claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    maker: "Anthropic",
    route: "AWS Bedrock EU / Vertex EU",
    tier: "B",
    mode: "configurable",
    openness: "proprietary",
    inputPrice: 3.0,
    outputPrice: 15.0,
    throughput: 90,
    ttft: 0.9,
    latest: true,
    note: "Hybrid extended thinking. Reasoning escalation path.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Two residency hosts (Bedrock 99.9% + Vertex). Use EU-geo profiles, never global.",
  },
  {
    id: "bedrock-nova-lite",
    name: "Amazon Nova Lite",
    maker: "Amazon",
    route: "AWS Bedrock EU",
    tier: "B",
    mode: "non-reasoning",
    openness: "proprietary",
    inputPrice: 0.06,
    outputPrice: 0.24,
    throughput: 160,
    ttft: 0.6,
    note: "Very cheap, EU residency.",
    slaPct: 99.9,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Bedrock 99.9% regional SLA.",
  },

  // ── Tier C · rejected for sensitive workloads (US entity / no hard-EU routing) ──
  {
    id: "groq-llama-3-3-70b",
    name: "Llama 3.3 70B (Groq)",
    maker: "Meta",
    route: "Groq public API",
    tier: "C",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.59,
    outputPrice: 0.79,
    throughput: 314,
    ttft: 0.92,
    note: "Helsinki EU DC exists, but public API isn't hard-EU. US entity.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Fast and reliable, but rejected on sovereignty — promotable to B− only via dedicated Equinix EU deployment.",
  },
  {
    id: "groq-llama-3-1-8b",
    name: "Llama 3.1 8B (Groq)",
    maker: "Meta",
    route: "Groq public API",
    tier: "C",
    mode: "non-reasoning",
    openness: "open-weight",
    inputPrice: 0.05,
    outputPrice: 0.08,
    throughput: 840,
    ttft: 0.3,
    note: "Extremely fast, but not hard-EU on the default endpoint.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "low",
    reliabilityNote: "Usable for non-sensitive synthetic/test data only.",
  },
  {
    id: "cerebras-cs3",
    name: "Cerebras (CS-3 cloud)",
    maker: "Cerebras",
    route: "Cerebras inference cloud",
    tier: "C",
    mode: "configurable",
    openness: "open-weight",
    inputPrice: 0.6,
    outputPrice: 0.8,
    throughput: 2000,
    ttft: 0.17,
    note: "'for Nations' = gov/on-prem. Public cloud is US-hosted.",
    slaPct: null,
    observedUptime: null,
    availabilityRisk: "medium",
    reliabilityNote: "Public Cerebras cloud is US-hosted; the EU 'for Nations' path isn't a public API for a solo engineer.",
  },
];
